// frontend/components/SessionListThumb.vue
<template>
  <span
    class="flex h-8 w-8 shrink-0 items-center justify-center overflow-hidden rounded-lg text-zinc-600 dark:text-zinc-300"
    :class="containerClass"
  >
    <!-- 一对一：单个头像或首字 -->
    <template v-if="type === 'private'">
      <img
        v-if="firstParticipant?.avatar"
        :src="firstParticipant.avatar"
        :alt="firstParticipant.name"
        class="h-full w-full object-cover"
      />
      <span v-else class="text-xs font-medium">
        {{ firstChar }}
      </span>
    </template>
    <!-- 一对多：四宫格，按排序前四个 -->
    <template v-else-if="type === 'group'">
      <span class="grid h-full w-full grid-cols-2 grid-rows-2 gap-px rounded-lg overflow-hidden bg-zinc-300 dark:bg-zinc-600">
        <span
          v-for="(p, i) in gridSlots"
          :key="i"
          class="flex items-center justify-center text-[10px] font-medium"
          :class="p?.kind === 'bot' ? 'bg-violet-100 dark:bg-violet-900/40 text-violet-600 dark:text-violet-400' : 'bg-amber-100 dark:bg-amber-900/40'"
        >
          <template v-if="p">
            <img
              v-if="p.avatar"
              :src="p.avatar"
              :alt="p.name"
              class="h-full w-full object-cover"
            />
            <Bot v-else-if="p.kind === 'bot'" class="h-2.5 w-2.5" />
            <span v-else>{{ (p.name || '').trim().charAt(0) || '?' }}</span>
          </template>
        </span>
      </span>
    </template>
  </span>
</template>

<script setup lang="ts">
import { Bot } from 'lucide-vue-next'

/** 与 MockParticipant 对齐：用户或 @ 拉入的机器人 */
export type SessionParticipant = { name: string; avatar?: string; kind?: 'user' | 'bot' }

const props = withDefaults(
  defineProps<{
    type: 'private' | 'group'
    participants?: SessionParticipant[]
  }>(),
  { participants: () => [] },
)

const firstParticipant = computed(() => props.participants?.[0])
const firstChar = computed(() => {
  const name = firstParticipant.value?.name ?? ''
  return (name.trim().charAt(0) || '?').toUpperCase()
})

/** 一对多时按排序取前 4 个，不足 4 个的格子留空 */
const gridSlots = computed(() => {
  const list = (props.participants ?? []).slice(0, 4)
  const slots: (SessionParticipant | null)[] = [...list]
  while (slots.length < 4) slots.push(null)
  return slots
})

const containerClass = computed(() =>
  props.type === 'group'
    ? 'bg-transparent p-0'
    : 'bg-zinc-200 dark:bg-zinc-600',
)
</script>

// apps/web/src/components/SessionListThumb.tsx
'use client';

import { Bot, Users } from 'lucide-react';
import { cn } from '@/lib/utils';

export type SessionParticipant = {
  name: string;
  avatar?: string;
  kind?: 'user' | 'bot';
};

export function SessionListThumb({
  type,
  participants = [],
  className,
}: {
  type: 'private' | 'group';
  participants?: SessionParticipant[];
  className?: string;
}) {
  const first = participants?.[0];
  const firstChar = first?.name?.trim?.()?.charAt(0)?.toUpperCase() ?? '?';

  if (type === 'private') {
    return (
      <span
        className={cn(
          'flex h-8 w-8 shrink-0 items-center justify-center overflow-hidden rounded-lg bg-zinc-100 text-zinc-600 dark:bg-zinc-600 dark:text-zinc-300',
          className
        )}
      >
        {first?.avatar ? (
          <img
            src={first.avatar}
            alt={first.name}
            className="h-full w-full object-cover"
          />
        ) : first?.kind === 'bot' ? (
          <Bot className="h-4 w-4" />
        ) : (
          <span className="text-xs font-medium">{firstChar}</span>
        )}
      </span>
    );
  }

  return (
    <span
      className={cn(
        'flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-300',
        className
      )}
    >
      <Users className="h-4 w-4" />
    </span>
  );
}
