// frontend/components/ChatInputPanel.vue
<template>
  <div class="absolute bottom-0 left-0 right-0 z-20 flex flex-col">
    <div
      class="h-16 pointer-events-none shrink-0 bg-gradient-to-t from-white to-transparent dark:from-zinc-800 dark:to-transparent"
      aria-hidden
    />
    <div class="shrink-0 p-3 pt-0 bg-white dark:bg-zinc-800">
      <div class="chat-input-card relative rounded-xl border border-zinc-200 dark:border-zinc-600 bg-white dark:bg-zinc-800 shadow-sm overflow-visible">
        <div
          v-if="streaming"
          class="flex items-center justify-between px-3 py-2 border-b border-zinc-100 dark:border-zinc-700"
        >
          <div class="flex items-center gap-2 text-xs text-zinc-500 dark:text-zinc-400">
            <button
              type="button"
              class="font-medium text-zinc-700 dark:text-zinc-300 hover:text-zinc-900 dark:hover:text-zinc-100"
              @click="$emit('stop')"
            >
              停止
            </button>
            <span>Ctrl+Shift+Enter 停止</span>
          </div>
          <div class="flex items-center gap-1">
            <button
              type="button"
              class="flex h-8 w-8 items-center justify-center rounded-lg text-zinc-500 hover:bg-zinc-100 dark:hover:bg-zinc-700 transition-colors"
              aria-label="清空输入"
              @click="$emit('clear')"
            >
              <X class="h-4 w-4" />
            </button>
            <button
              type="button"
              class="rounded-lg px-3 py-1.5 text-sm font-medium text-zinc-700 dark:text-zinc-300 bg-zinc-100 dark:bg-zinc-700 hover:bg-zinc-200 dark:hover:bg-zinc-600 transition-colors"
              @click="$emit('scroll-to-last')"
            >
              回顾
            </button>
          </div>
        </div>
        <!-- 顶部外侧悬浮把手：不占编辑框空间 -->
        <button
          type="button"
          class="chat-input-resize-handle absolute left-1/2 top-0 z-10 flex -translate-x-1/2 -translate-y-full cursor-n-resize items-center justify-center rounded-t-md rounded-b-none border border-zinc-200 dark:border-zinc-600 border-b-0 bg-white dark:bg-zinc-700 hover:bg-zinc-50 dark:hover:bg-zinc-600 transition-colors py-px px-3 text-zinc-500 hover:text-zinc-700 dark:text-zinc-400 dark:hover:text-zinc-200"
          aria-label="拖拽调整输入框高度"
          @mousedown.prevent="onResizeStart"
        >
          <GripHorizontal class="h-2 w-2" />
        </button>
        <form class="flex flex-col overflow-hidden rounded-xl" @submit.prevent="$emit('submit')">
          <div
            ref="textareaWrapRef"
            class="chat-input-inner-scroll overflow-x-hidden"
            :class="modelValue.trim() ? 'overflow-y-auto' : 'overflow-y-hidden'"
            :style="{ height: `${editHeightPx}px` }"
          >
            <textarea
              ref="textareaRef"
              :value="modelValue"
              rows="2"
              placeholder="说点什么？"
              class="chat-input-textarea min-h-[72px] w-full resize-none border-0 bg-transparent pl-3 pr-1 py-3 text-sm text-zinc-800 dark:text-zinc-200 placeholder-zinc-400 dark:placeholder-zinc-500 focus:outline-none focus:ring-0"
              :disabled="streaming"
              @input="onTextareaInput"
              @keydown.enter.exact.prevent="$emit('submit')"
              @keydown.enter.shift.exact.prevent="$emit('update:modelValue', modelValue + '\n')"
            />
          </div>
          <div class="flex items-center justify-between gap-2 px-3 pb-2 pt-0">
            <div class="flex items-center gap-2">
              <button
                type="button"
                class="flex items-center gap-1.5 rounded-lg border border-zinc-200 dark:border-zinc-600 bg-zinc-50 dark:bg-zinc-700/50 px-2.5 py-1.5 text-xs font-medium text-zinc-700 dark:text-zinc-300 hover:bg-zinc-100 dark:hover:bg-zinc-700 transition-colors"
              >
                <Infinity class="h-3.5 w-3.5" />
                <span>Agent</span>
                <ChevronDown class="h-3.5 w-3.5 opacity-60" />
              </button>
              <button
                type="button"
                class="flex items-center gap-1.5 rounded-lg border border-zinc-200 dark:border-zinc-600 bg-zinc-50 dark:bg-zinc-700/50 px-2.5 py-1.5 text-xs font-medium text-zinc-700 dark:text-zinc-300 hover:bg-zinc-100 dark:hover:bg-zinc-700 transition-colors"
              >
                <span>自动</span>
                <ChevronDown class="h-3.5 w-3.5 opacity-60" />
              </button>
            </div>
            <div class="flex items-center gap-1">
              <span
                v-if="streaming"
                class="flex h-8 w-8 items-center justify-center text-zinc-400"
                aria-hidden
              >
                <Loader2 class="h-4 w-4 animate-spin" />
              </span>
              <button
                type="button"
                class="flex h-8 w-8 items-center justify-center rounded-lg text-zinc-500 hover:bg-zinc-100 dark:hover:bg-zinc-700 transition-colors"
                title="向当前会话加人/机器人"
                aria-label="向当前会话加人/机器人"
                @click="$emit('add-participant')"
              >
                <AtSign class="h-4 w-4 text-primary-500" />
              </button>
              <button
                type="button"
                class="flex h-8 w-8 items-center justify-center rounded-lg text-zinc-500 hover:bg-zinc-100 dark:hover:bg-zinc-700 transition-colors"
                title="图片"
                aria-label="上传图片"
              >
                <ImageIcon class="h-4 w-4" />
              </button>
              <button
                v-if="streaming"
                type="button"
                class="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg text-zinc-500 hover:bg-zinc-100 dark:hover:bg-zinc-700 transition-colors"
                aria-label="停止"
                @click="$emit('stop')"
              >
                <Square class="h-4 w-4" />
              </button>
              <button
                v-else
                type="submit"
                class="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg text-zinc-500 hover:bg-zinc-100 dark:hover:bg-zinc-700 transition-colors disabled:opacity-50 disabled:pointer-events-none"
                :disabled="!modelValue.trim()"
                aria-label="发送"
              >
                <Send class="h-4 w-4" />
              </button>
            </div>
          </div>
        </form>
      </div>
      <p class="mt-2 flex items-center justify-center gap-1.5 text-[10px] text-zinc-500 dark:text-zinc-400 text-center">
        AI 的回答未必正确无误，请注意核查
      </p>
    </div>
  </div>
</template>

<script setup lang="ts">
import { AtSign, ChevronDown, GripHorizontal, Image as ImageIcon, Infinity, Loader2, Send, Square, X } from 'lucide-vue-next'
import { ref, watch, onMounted, onUnmounted, nextTick } from 'vue'

const props = defineProps<{
  modelValue: string
  streaming: boolean
}>()
const emit = defineEmits<{
  (e: 'update:modelValue', value: string): void
  (e: 'submit'): void
  (e: 'stop'): void
  (e: 'clear'): void
  (e: 'scroll-to-last'): void
  (e: 'add-participant'): void
}>()

const MIN_EDIT_HEIGHT = 72
const MAX_EDIT_HEIGHT = 280
const DEFAULT_EDIT_HEIGHT = 72

const textareaWrapRef = ref<HTMLElement | null>(null)
const textareaRef = ref<HTMLTextAreaElement | null>(null)
const editHeightPx = ref(DEFAULT_EDIT_HEIGHT)

function adjustTextareaHeight() {
  nextTick(() => {
    const el = textareaRef.value
    if (!el) return
    el.style.overflow = 'hidden'
    el.style.height = '0'
    const h = Math.max(MIN_EDIT_HEIGHT, el.scrollHeight)
    el.style.height = `${h}px`
    el.style.overflow = 'hidden'
    // 空内容时让外层高度与 textarea 一致，避免出现滚动条
    if (!props.modelValue.trim()) {
      editHeightPx.value = h
    }
  })
}

function onTextareaInput(e: Event) {
  const value = (e.target as HTMLTextAreaElement).value
  emit('update:modelValue', value)
  adjustTextareaHeight()
}

watch(() => props.modelValue, adjustTextareaHeight)
onMounted(adjustTextareaHeight)

let resizeStartY = 0
let resizeStartHeight = 0

function onResizeStart(e: MouseEvent) {
  resizeStartY = e.clientY
  resizeStartHeight = editHeightPx.value
  window.addEventListener('mousemove', onResizeMove)
  window.addEventListener('mouseup', onResizeEnd)
}

function onResizeMove(e: MouseEvent) {
  const delta = resizeStartY - e.clientY
  const next = Math.min(MAX_EDIT_HEIGHT, Math.max(MIN_EDIT_HEIGHT, resizeStartHeight + delta))
  editHeightPx.value = next
}

function onResizeEnd() {
  window.removeEventListener('mousemove', onResizeMove)
  window.removeEventListener('mouseup', onResizeEnd)
}

onUnmounted(() => {
  window.removeEventListener('mousemove', onResizeMove)
  window.removeEventListener('mouseup', onResizeEnd)
})
</script>

<style scoped>
.chat-input-inner-scroll {
  scrollbar-gutter: stable;
}
/* 空内容时不预留滚动条、不显示滚动条 */
.chat-input-inner-scroll.overflow-y-hidden {
  scrollbar-gutter: auto;
}
.chat-input-inner-scroll::-webkit-scrollbar {
  width: 2px;
}
.chat-input-inner-scroll::-webkit-scrollbar-track {
  background: transparent;
}
.chat-input-inner-scroll::-webkit-scrollbar-thumb {
  border-radius: 4px;
  background: rgb(161 161 170 / 0.4);
}
.chat-input-inner-scroll::-webkit-scrollbar-thumb:hover {
  background: rgb(161 161 170 / 0.6);
}
.chat-input-inner-scroll::-webkit-scrollbar-thumb:active {
  background: rgb(161 161 170 / 0.8);
}
@supports (scrollbar-width: thin) {
  .chat-input-inner-scroll {
    scrollbar-width: thin;
    scrollbar-color: rgb(161 161 170 / 0.5) transparent;
  }
}
/* 仅外层滚动，textarea 不出现第二条滚动条 */
.chat-input-textarea {
  overflow: hidden;
}
</style>

// apps/web/src/components/chat/ChatInputPanel.tsx
'use client';

import { GripHorizontal, SendHorizontal } from 'lucide-react';
import { useRef, useEffect, useState, useCallback } from 'react';
import { cn } from '@/lib/utils';
import type { MentionItem } from '@/hooks/useContactsAndBots';
import { ChatLexicalEditor } from '@/components/chat/lexical/ChatLexicalEditor';

/** 最小高度 100px，需容纳容器 padding、编辑器、底部工具栏 */
const MIN_EDIT_HEIGHT_PX = 100;
const MAX_EDIT_HEIGHT_PX = 280;
const DEFAULT_EDIT_HEIGHT_PX = 100;

export interface ChatInputPanelProps {
  value: string;
  onChange: (value: string) => void;
  onSubmit?: () => void;
  placeholder?: string;
  disabled?: boolean;
  /** true = Enter 发送 / Shift+Enter 换行，false = Enter 换行 / Ctrl+Enter 发送，默认 true */
  enterToSend?: boolean;
  /** @ 提及菜单项（联系人 + AI 助手），与 frontend UEditorMentionMenu 一致；Lexical 始终启用，无项时仅无候选 */
  mentionItems?: MentionItem[];
  /** 输入区高度变化时上报（px），用于聊天区底部留白 */
  onHeightChange?: (heightPx: number) => void;
  className?: string;
}

const DEFAULT_PLACEHOLDER = '说点什么？';
const MENTION_PLACEHOLDER = '说点什么？输入 @ 可提及联系人或机器人';

export function ChatInputPanel({
  value,
  onChange,
  onSubmit,
  placeholder,
  disabled = false,
  enterToSend = true,
  mentionItems = [],
  onHeightChange,
  className,
}: ChatInputPanelProps) {
  const rootRef = useRef<HTMLDivElement>(null);
  const [editHeightPx, setEditHeightPx] = useState(DEFAULT_EDIT_HEIGHT_PX);
  const resolvedPlaceholder =
    placeholder ?? (mentionItems.length > 0 ? MENTION_PLACEHOLDER : DEFAULT_PLACEHOLDER);

  useEffect(() => {
    onHeightChange?.(editHeightPx);
  }, [editHeightPx, onHeightChange]);

  const resizeStartYRef = useRef(0);
  const resizeStartHeightRef = useRef(0);

  const onResizeMoveRef = useRef((e: MouseEvent) => {
    const delta = resizeStartYRef.current - e.clientY;
    const next = Math.min(
      MAX_EDIT_HEIGHT_PX,
      Math.max(MIN_EDIT_HEIGHT_PX, resizeStartHeightRef.current + delta)
    );
    setEditHeightPx(next);
  });

  const onResizeEndRef = useRef(() => {
    window.removeEventListener('mousemove', onResizeMoveRef.current);
    window.removeEventListener('mouseup', onResizeEndRef.current);
  });

  const onResizeStart = useCallback((e: React.MouseEvent) => {
    e.preventDefault();
    resizeStartYRef.current = e.clientY;
    resizeStartHeightRef.current = editHeightPx;
    window.addEventListener('mousemove', onResizeMoveRef.current);
    window.addEventListener('mouseup', onResizeEndRef.current);
  }, [editHeightPx]);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!disabled && value.trim()) onSubmit?.();
  };

  return (
    <div
      ref={rootRef}
      className={cn('absolute bottom-0 left-0 right-0 z-20 flex flex-col pointer-events-none', className)}
    >
      <button
        type="button"
        className="chat-input-resize-handle absolute left-1/2 top-[1px] z-10 flex -translate-x-1/2 -translate-y-full cursor-n-resize items-center justify-center rounded-t-md rounded-b-none border border-zinc-200 border-b-0 bg-white py-px px-3 text-black transition-colors hover:bg-zinc-50 hover:text-black dark:border-zinc-600 dark:bg-white dark:text-zinc-900 dark:hover:bg-zinc-100 dark:hover:text-zinc-900 pointer-events-auto"
        aria-label="拖拽调整输入框高度"
        onMouseDown={onResizeStart}
      >
        <GripHorizontal className="h-2 w-2" aria-hidden />
      </button>
      <div
        className="flex shrink-0 flex-col px-3 pointer-events-auto overflow-hidden"
        style={{ height: editHeightPx, minHeight: editHeightPx }}
      >
        <form onSubmit={handleSubmit} className="flex h-full min-h-0 flex-col overflow-hidden">
          <div className="flex flex-1 min-h-0 flex-col rounded-xl border border-border bg-white/70 px-2 py-2 overflow-hidden backdrop-blur-md dark:bg-zinc-900/70">
            <ChatLexicalEditor
              value={value}
              onChange={onChange}
              onSubmit={onSubmit}
              placeholder={resolvedPlaceholder}
              disabled={disabled}
              enterToSend={enterToSend}
              mentionItems={mentionItems}
              toolbarExtra={
                <div className="flex items-center gap-2">
                  <span className="text-[10px] text-muted-foreground whitespace-nowrap" aria-hidden>
                    {enterToSend ? 'Shift + Enter 换行' : 'Ctrl + Enter 发送'}
                  </span>
                  <div
                    className={cn(
                      'send-btn-wrap rounded-lg p-0.5 transition-colors duration-300',
                      !disabled && value.trim() && 'send-btn-ready'
                    )}
                  >
                    <button
                      type="submit"
                      className={cn(
                        'send-btn-inner group relative flex h-6 min-w-8 items-center justify-center gap-0.5 rounded-[calc(0.5rem-1px)] pl-1 pr-1.5 transition-colors duration-200 disabled:pointer-events-none disabled:opacity-50',
                        !disabled && value.trim()
                          ? 'bg-white text-black shadow-md ring-1 ring-primary-200/50 hover:bg-zinc-50 dark:bg-zinc-800 dark:text-white dark:ring-primary-400/25 dark:hover:bg-zinc-700'
                          : 'bg-white text-black hover:bg-zinc-50 hover:text-black dark:bg-zinc-800 dark:text-white dark:hover:bg-zinc-700 dark:hover:text-white'
                      )}
                      disabled={disabled || !value.trim()}
                      aria-label="发送"
                    >
                      <span className="flex shrink-0 pl-0.5 transition-transform duration-200 group-hover:-rotate-90">
                        <SendHorizontal className="h-3 w-3" aria-hidden />
                      </span>
                      <span className="text-[10px] font-medium">发送</span>
                    </button>
                  </div>
                </div>
              }
              className="min-w-0"
            />
          </div>
        </form>
      </div>
    </div>
  );
}
